{% set name = "pyemf3" %}
{% set version = "3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/jeremysanders/pyemf3/archive/v{{ version }}.tar.gz
  sha256: 59dde1609ac1bb586c6fccaf47183ba8cb46d9d7570d51f1cba19aada82a0cf4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  
requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
   
test:
  requires:
    - python {{ python_min }}
  imports:
    - pyemf3
  
about:
  home: https://github.com/jeremysanders/pyemf3
  description: |
    pyemf3 is a pure python module that provides bindings for an ECMA-234
    compliant vector graphics library.  ECMA-234 is the published
    interface for the Windows GDI used in the Microsoft windows
    environment and, more importantly, natively supported by the
    OpenOffice suite of tools.
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: "Pure Python Enhanced Metafile Library"
  doc_url: 
  dev_url: https://github.com/jeremysanders/pyemf3

extra:
  recipe-maintainers:
    - n-elie
